### ISSUE TITLE
Cannot find module  './dom'

### ISSUE THREAD

**Issue by alirazaalvi** [helion3/inspire-tree-react-demo#1]
I am using gulp with browserify. Whenever i runs the gulp command i get 'Cannot find module  './dom'
error message.

**Comment by viveleroi** [comment]
Can you clarify your setup? You're filing the issue for the react demo which doesn't use either of those tools. Are you using gulp/browserify with inspire-tree directly, or with this actual project?

If you're doing a custom build of inspire tree, you'll need to set a variable of `DOM=false` in the final output, otherwise the source will [try to load our custom dom module](https://github.com/helion3/inspire-tree/blob/master/src/tree.js#L142).

**Comment by alirazaalvi** [comment]
Yes i am using inspire-tree directly with gulp and browserify.

I installed inspire-tree using npm by using
npm install -save inspire-tree

Then in my component i am simply importing it like following lines

import InspireTree from 'inspire-tree/dist/inspire-tree-core';
import 'inspire-tree/dist/inspire-tree.css';

So where to set DOM=false?

**Comment by viveleroi** [comment]
This should be filed against inspire tree itself: https://github.com/helion3/inspire-tree

Don't worry about that now though.

I'm not sure how you're getting that error. By importing the core file directly, `DOM` will be undefined, meaning the `require('./dom')` should not be called. I wonder if browserify parses all `require` calls regardless of conditionals.

I'll have to look into it.

**Comment by viveleroi** [comment]
Ok, after a quick search it looks like browserify will _always_ load `require` calls whether they're conditional or not. This is a common issue so folks have made several recommendations:
- browserify's `ignore` option will simply replace the module you don't want to bundle by an empty stub, and bundle that instead
- `exclude` will exclude the module altogether, your code will then throw a "not found" error if you try to import it.

**Comment by viveleroi** [comment]
You could probably also use `--ignore-missing`

**Comment by viveleroi** [comment]
Looks like the ignore/exclude options work, but only if the file is present, which defeats half their purpose in my opinion.

You can always use `--ignore-missing`, but that could potentially mask errors you want to know about.

Since the ignore option requires the file to be present, you could switch your import to the src files `import InspireTree from 'inspire-tree/src/tree'`. The `ignore` option should then work since the dom.js file would be _present_. The only caveat now is you'd have to also exclude `lodash` unless you want that bundled.

**Comment by viveleroi** [comment]
I dislike this, but the easiest solution on my end is to publish an empty `dom.js` file in the dist directory and then advise the use of `ignore` for browserify users.
